[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\temp\dbuck\testbuild'

[dependencies.testbuild-deps]
libraries = ['PPL.lvlibp']
copy_location = 'includes'

[dependencies.local]
libraries = ['Built\lvBuildInternalDep\win\InternalDep.lvlibp']
copy_location = 'includes'

[projects.lvBuildSpec]
path = 'src\lvBuildSpec.lvproj'

[projects.lvBuildSpecAllTargets]
path = 'src\lvBuildSpecAllTargets.lvproj'

[projects.lvBuildAll]
path = 'src\lvBuildAll.lvproj'

[projects.lvSetConditionalSymbol]
path = 'src\lvSetConditionalSymbol.lvproj'

[projects.lvBuildDeps]
path = 'src\lvBuildDeps.lvproj'

[[codegen.steps]]
name = 'Set Conditional Disable'
type = 'lvSetConditionalSymbol'
project = '{lvSetConditionalSymbol}'
symbol = 'symbol'
true_value = 'set'
false_value = 'unset'
condition = 'lvVersion < 2017'

[[codegen.steps]]
name = 'Run VI Codegen Test'
type = 'lvRunVi'
vi = 'src\helloworld.vi'

[[build.steps]]
name = 'Test Build Spec'
type = 'lvBuildSpec'
project = '{lvBuildSpec}'
target = 'My Computer'
build_spec = 'SourceDist'

[[build.steps]]
name = 'Test Build Spec All Targets'
type = 'lvBuildSpecAllTargets'
project = '{lvBuildSpecAllTargets}'
build_spec = 'SourceDist'

[[build.steps]]
name = 'Test Build All'
type = 'lvBuildAll'
project = '{lvBuildAll}'

[[build.steps]]
name = 'Test Dependencies'
type = 'lvBuildSpec'
project = '{lvBuildDeps}'
target = 'My Computer'
build_spec = 'SourceDist'
dependency_target = 'win'

[package]
type = 'nipkg'
payload_dir = 'Built'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}\Custom Devices'
