[paths]
BUILT_DIR = 'Built'
ARCHIVE_DIR = '\\nirvana\temp\dbuck\testbuild'

[projects.lvBuildSpec]
path = 'src\lvBuildSpec.lvproj'

[projects.lvBuildSpecAllTargets]
path = 'src\lvBuildSpecAllTargets.lvproj'

[[mkdirectories]]
path = 'Built'

[exports]
Jenkinsfile = 'Built\Jenkinsfile'
configfile = 'Built\mytest.lvproj.config'

[[build.steps]]
name = 'Test Build Spec'
type = 'lvBuildSpec'
project = '{lvBuildSpec}'
target = 'My Computer'
build_spec = 'SourceDist'

[[build.steps]]
name = 'Test Build Spec All Targets'
type = 'lvBuildSpecAllTargets'
project = '{lvBuildSpecAllTargets}'
build_spec = 'SourceDist'

[[build.steps]]
name = 'Project path'
type = 'lvBuildSpec'
project = 'src\lvBuildSpec.lvproj'
target = 'My Computer'
build_spec = 'Executable'

[package]
type = 'nipm'
