[archive]
build_output_dir = 'Built'
archive_location = '\\nirvana\temp\dbuck\testbuild'

[projects.lvBuildSpec]
path = 'src\lvBuildSpec.lvproj'

[projects.lvBuildSpecAllTargets]
path = 'src\lvBuildSpecAllTargets.lvproj'

[projects.lvBuildAll]
path = 'src\lvBuildAll.lvproj'

[projects.lvSetConditionalSymbol]
path = 'src\lvSetConditionalSymbol.lvproj'

[[codegen.steps]]
name = 'Set Conditional Disable'
type = 'lvSetConditionalSymbol'
project = '{lvSetConditionalSymbol}'
symbol = 'symbol'
true_value = 'set'
false_value = 'unset'
condition = 'lvVersion < 2017'

[[codegen.steps]]
name = 'Run VI Codegen Test'
type = 'lvRunVi'
vi = 'src\helloworld.vi'

[[build.steps]]
name = 'Test Build Spec'
type = 'lvBuildSpec'
project = '{lvBuildSpec}'
target = 'My Computer'
build_spec = 'SourceDist'

[[build.steps]]
name = 'Test Build Spec All Targets'
type = 'lvBuildSpecAllTargets'
project = '{lvBuildSpecAllTargets}'
build_spec = 'SourceDist'

[[build.steps]]
name = 'Test Build All'
type = 'lvBuildAll'
project = '{lvBuildAll}'

[package]
type = 'nipkg'
name = 'testbuild'
version = '1.0'
maintainer = 'Donovan Buck (donovan.buck@ni.com)'
description = 'NIPKG for the testbuild component. Installs all items built for testbuild.'
homepage = 'www.ni.com'
display_name = 'Custom Device Pipeline Test Build'
eula_dependency = 'eula-pkg'
dependencies = ['pkg1', 'pkg2']
